#if !defined(AFX_ILEDRECTANGLEX_H__620CE9D7_3896_11D4_8161_0050BAD1675F__INCLUDED_)
#define AFX_ILEDRECTANGLEX_H__620CE9D7_3896_11D4_8161_0050BAD1675F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CiLedRectangleX wrapper class

class CiLedRectangleX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CiLedRectangleX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa362345, 0x2e5e, 0x11d3, { 0x85, 0xbf, 0x0, 0x10, 0x5a, 0xc8, 0xb7, 0x15 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	unsigned long GetActiveColor();
	void SetActiveColor(unsigned long newValue);
	long GetBevelStyle();
	void SetBevelStyle(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	void AboutBox();
	void ShowPropertyEditor();
	CString GetCenterLabelText();
	void SetCenterLabelText(LPCTSTR lpszNewValue);
	COleFont GetCenterLabelFont();
	void SetCenterLabelFont(LPDISPATCH newValue);
	unsigned long GetCenterLabelFontActiveColor();
	void SetCenterLabelFontActiveColor(unsigned long newValue);
	unsigned long GetCenterLabelFontInactiveColor();
	void SetCenterLabelFontInactiveColor(unsigned long newValue);
	void SetActiveNoEvent(BOOL Value);
	BOOL GetShowReflection();
	void SetShowReflection(BOOL bNewValue);
	BOOL GetAutoInactiveColor();
	void SetAutoInactiveColor(BOOL bNewValue);
	unsigned long GetInactiveColor();
	void SetInactiveColor(unsigned long newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ILEDRECTANGLEX_H__620CE9D7_3896_11D4_8161_0050BAD1675F__INCLUDED_)
