#if !defined(AFX_ISEVENSEGMENTANALOGX_H__6C793834_5632_4C6B_9DC8_F0B49642E642__INCLUDED_)
#define AFX_ISEVENSEGMENTANALOGX_H__6C793834_5632_4C6B_9DC8_F0B49642E642__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CiSevenSegmentAnalogX wrapper class

class CiSevenSegmentAnalogX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CiSevenSegmentAnalogX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc5412e33, 0x2e2f, 0x11d3, { 0x85, 0xbf, 0x0, 0x10, 0x5a, 0xc8, 0xb7, 0x15 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetPrecision();
	void SetPrecision(long nNewValue);
	double GetValue();
	void SetValue(double newValue);
	BOOL GetShowSign();
	void SetShowSign(BOOL bNewValue);
	long GetDigitCount();
	void SetDigitCount(long nNewValue);
	long GetLeadingStyle();
	void SetLeadingStyle(long nNewValue);
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	long GetDigitSpacing();
	void SetDigitSpacing(long nNewValue);
	long GetSegmentMargin();
	void SetSegmentMargin(long nNewValue);
	unsigned long GetSegmentColor();
	void SetSegmentColor(unsigned long newValue);
	long GetSegmentSeperation();
	void SetSegmentSeperation(long nNewValue);
	long GetSegmentSize();
	void SetSegmentSize(long nNewValue);
	BOOL GetShowOffSegments();
	void SetShowOffSegments(BOOL bNewValue);
	BOOL GetPowerOff();
	void SetPowerOff(BOOL bNewValue);
	unsigned long GetBackGroundColor();
	void SetBackGroundColor(unsigned long newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	void AboutBox();
	void ShowPropertyEditor();
	void SetValueNoEvent(double Value);
	unsigned long GetSegmentOffColor();
	void SetSegmentOffColor(unsigned long newValue);
	BOOL GetAutoSegmentOffColor();
	void SetAutoSegmentOffColor(BOOL bNewValue);
	BOOL GetTransparent();
	void SetTransparent(BOOL bNewValue);
	void RepaintAll();
	void BeginUpdate();
	void EndUpdate();
	void Lock();
	void Unlock();
	long GetUpdateFrameRate();
	void SetUpdateFrameRate(long nNewValue);
	long GetComponentHandle();
	void SaveImageToBitmap(LPCTSTR FileName);
	void SaveImageToMetaFile(LPCTSTR FileName);
	void SaveImageToJPEG(LPCTSTR FileName, long Compression, BOOL Progressive);
	long OPCAddItem();
	long OPCItemCount();
	void OPCRemoveAllItems();
	void OPCItemActivate(long Index);
	void OPCItemDeactivate(long Index);
	CString GetOPCItemComputerName(long Index);
	CString GetOPCItemServerName(long Index);
	CString GetOPCItemItemName(long Index);
	CString GetOPCItemPropertyName(long Index);
	BOOL GetOPCItemAutoConnect(long Index);
	long GetOPCItemUpdateRate(long Index);
	void SetOPCItemComputerName(long Index, LPCTSTR Value);
	void SetOPCItemServerName(long Index, LPCTSTR Value);
	void SetOPCItemItemName(long Index, LPCTSTR Value);
	void SetOPCItemPropertyName(long Index, LPCTSTR Value);
	void SetOPCItemAutoConnect(long Index, BOOL Value);
	void SetOPCItemUpdateRate(long Index, long Value);
	void OPCItemLoaded(long Index);
	long GetObjectPointer();
	VARIANT GetBytesJPEG(long Compression, BOOL Progressive);
	void SavePropertiesToFile(LPCTSTR FileName);
	void LoadPropertiesFromFile(LPCTSTR FileName);
	BOOL GetOptionSaveAllProperties();
	void SetOptionSaveAllProperties(BOOL bNewValue);
	BOOL GetAutoFrameRate();
	void SetAutoFrameRate(BOOL bNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void iPaintToDC(long X, long Y, BOOL Transparent, long DC);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	void OPCItemUpdateResume(long Index);
	void OPCItemUpdateSuspend(long Index);
	VARIANT GetOPCItemData(long Index);
	short GetOPCItemQuality(long Index);
	double GetOPCItemTimeStamp(long Index);
	void SetOPCItemData(long Index, const VARIANT& Value);
	BOOL GetOPCItemActive(long Index);
	CString GetOPCItemGroupName(long Index);
	void SetOPCItemGroupName(long Index, LPCTSTR Value);
	void OPCDeleteItem(long Index);
	void OPCItemActivateSuspend(long Index);
	VARIANT GetBytesPNG(long Compression);
	void SaveImageToPNG(LPCTSTR FileName, long Compression);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ISEVENSEGMENTANALOGX_H__6C793834_5632_4C6B_9DC8_F0B49642E642__INCLUDED_)
